from . import DataType

def string() -> DataType: ...
def is_null(t: DataType) -> bool: ...
def is_string(t: DataType) -> bool: ...
def is_large_string(t: DataType) -> bool: ...
def is_struct(t: DataType) -> bool: ...
def is_boolean(t: DataType) -> bool: ...
def is_decimal(t: DataType) -> bool: ...
def is_floating(t: DataType) -> bool: ...
def is_integer(t: DataType) -> bool: ...
def is_date(t: DataType) -> bool: ...
def is_time(t: DataType) -> bool: ...
def is_timestamp(t: DataType) -> bool: ...
def is_duration(t: DataType) -> bool: ...
def is_binary(t: DataType) -> bool: ...
def is_map(t: DataType) -> bool: ...
def is_list(t: DataType) -> bool: ...
